version: "3.9"

services:
  tour-forecast-db:
    container_name: tour-forecast-db
    image: influxdb:latest
    ports:
      - "8086:8086"
    env_file:
      - backend/.env.influxdb
    volumes:
      - influxdata:/var/lib/influxdb
    restart: on-failure
    networks:
      - private_network

  tour-forecast-cache:
    container_name: tour-forecast-cache
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - redisconfig:/etc/redis
    restart: on-failure
    networks:
      - private_network

  tour-forecast-api:
    container_name: tour-forecast-api
    build:
      context: ./backend
    working_dir: /backend
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - backend/.env
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - public_network
      - private_network
    depends_on:
      - tour-forecast-db
      - tour-forecast-cache

volumes:
  influxdata:
  redisdata:
  redisconfig:

networks:
  private_network:
  public_network:
