version: "3.9"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    env_file:
      - backend/.env.influxdb
    volumes:
      - influxdata:/var/lib/influxdb
    restart: on-failure
    networks:
      - private_network

  tour-forecast-api:
    container_name: tour-forecast-api
    build:
      context: ./backend
    working_dir: /backend
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - backend/.env
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - public_network
      - private_network

volumes:
  influxdata:

networks:
  private_network:
  public_network:
